<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SQA-CRS-021" ignored="0" name="Test" tests="7" failures="7" timestamp="29 Apr 2020 18:35:06 GMT" time="223.785" errors="0">
  <testcase name="testMethod1" time="88.517" classname="prerate.prerateTestNGSlow">
    <failure type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException" message="Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@f14f3">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@f14f3
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:602)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at configuration.excel.writeCellData(excel.java:174)
	at prerate.prerateTestNGSlow.writeToExcel(prerateTestNGSlow.java:828)
	at prerate.prerateTestNGSlow.doPrerate(prerateTestNGSlow.java:813)
	at prerate.prerateTestNGSlow.testMethod1(prerateTestNGSlow.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@f14f3
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:590)
	... 19 more
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod1" time="1.374" classname="prerate.prerateTestNGSlow">
    <failure type="org.openqa.selenium.WebDriverException" message="unknown error: failed to write prefs file
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 41 milliseconds
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:25:48&amp;apos;
System info: host: &amp;apos;SQA-CRS-021&amp;apos;, ip: &amp;apos;10.255.251.244&amp;apos;, os.name: &amp;apos;Windows 7&amp;apos;, os.arch: &amp;apos;x86&amp;apos;, os.version: &amp;apos;6.1&amp;apos;, java.version: &amp;apos;1.8.0_212&amp;apos;
Driver info: driver.version: ChromeDriver">
      <![CDATA[org.openqa.selenium.WebDriverException: unknown error: failed to write prefs file
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 41 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'SQA-CRS-021', ip: '10.255.251.244', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_212'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$errorHandler$0(JsonWireProtocolResponse.java:54)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at prerate.prerateTestNGSlow.testMethod1(prerateTestNGSlow.java:328)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod3" time="92.817" classname="prerate.prerateTestNGSlow">
    <failure type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException" message="Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@f14f3">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@f14f3
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:602)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at configuration.excel.writeCellData(excel.java:174)
	at prerate.prerateTestNGSlow.writeToExcel(prerateTestNGSlow.java:828)
	at prerate.prerateTestNGSlow.doPrerate(prerateTestNGSlow.java:813)
	at prerate.prerateTestNGSlow.testMethod3(prerateTestNGSlow.java:415)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@f14f3
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:590)
	... 19 more
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testMethod3 -->
  <testcase name="testMethod4" time="144.433" classname="prerate.prerateTestNGSlow">
    <failure type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException" message="Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@f14f3">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@f14f3
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:602)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at configuration.excel.writeCellData(excel.java:174)
	at prerate.prerateTestNGSlow.writeToExcel(prerateTestNGSlow.java:828)
	at prerate.prerateTestNGSlow.doPrerate(prerateTestNGSlow.java:813)
	at prerate.prerateTestNGSlow.testMethod4(prerateTestNGSlow.java:460)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@f14f3
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:590)
	... 19 more
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testMethod4 -->
  <testcase name="testMethod2" time="147.7" classname="prerate.prerateTestNGSlow">
    <failure type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException" message="Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@f14f3">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@f14f3
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:602)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at configuration.excel.writeCellData(excel.java:174)
	at prerate.prerateTestNGSlow.writeToExcel(prerateTestNGSlow.java:828)
	at prerate.prerateTestNGSlow.doPrerate(prerateTestNGSlow.java:813)
	at prerate.prerateTestNGSlow.testMethod2(prerateTestNGSlow.java:374)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@f14f3
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:590)
	... 19 more
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testMethod2 -->
  <testcase name="testMethod3" time="70.815" classname="prerate.prerateTestNGSlow">
    <failure type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException" message="Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@f14f3">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@f14f3
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:602)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1557)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at configuration.excel.writeCellData(excel.java:174)
	at prerate.prerateTestNGSlow.writeToExcel(prerateTestNGSlow.java:828)
	at prerate.prerateTestNGSlow.doPrerate(prerateTestNGSlow.java:813)
	at prerate.prerateTestNGSlow.testMethod3(prerateTestNGSlow.java:415)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@f14f3
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:590)
	... 19 more
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testMethod3 -->
  <testcase name="testMethod2" time="74.068" classname="prerate.prerateTestNGSlow">
    <failure type="java.lang.AssertionError" message="No Error Found, but still failed">
      <![CDATA[java.lang.AssertionError: No Error Found, but still failed
	at prerate.prerateTestNGSlow.doPrerate(prerateTestNGSlow.java:814)
	at prerate.prerateTestNGSlow.testMethod2(prerateTestNGSlow.java:374)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testMethod2 -->
</testsuite> <!-- Test -->
