<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SQA-CRS-021" ignored="0" name="Prerate Test" tests="4" failures="4" timestamp="27 Apr 2020 19:55:33 GMT" time="108.141" errors="0">
  <testcase name="testMethod4" time="70.586" classname="prerate.prerateTestNGSlow">
    <failure type="java.lang.AssertionError" message="Override Disabled.">
      <![CDATA[java.lang.AssertionError: Override Disabled.
	at prerate.prerateTestNGSlow.doPrerate(prerateTestNGSlow.java:725)
	at prerate.prerateTestNGSlow.testMethod4(prerateTestNGSlow.java:439)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testMethod4 -->
  <testcase name="testMethod3" time="73.147" classname="prerate.prerateTestNGSlow">
    <failure type="java.lang.AssertionError" message="Override Disabled.">
      <![CDATA[java.lang.AssertionError: Override Disabled.
	at prerate.prerateTestNGSlow.doPrerate(prerateTestNGSlow.java:725)
	at prerate.prerateTestNGSlow.testMethod3(prerateTestNGSlow.java:394)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testMethod3 -->
  <testcase name="testMethod1" time="93.729" classname="prerate.prerateTestNGSlow">
    <failure type="java.lang.AssertionError" message="Technical Error Occurred in Edits; Try again ,3334">
      <![CDATA[java.lang.AssertionError: Technical Error Occurred in Edits; Try again ,3334
	at prerate.prerateTestNGSlow.doPrerate(prerateTestNGSlow.java:765)
	at prerate.prerateTestNGSlow.testMethod1(prerateTestNGSlow.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <testcase name="testMethod2" time="107.211" classname="prerate.prerateTestNGSlow">
    <failure type="java.lang.AssertionError" message="No Error Found, but still failed">
      <![CDATA[java.lang.AssertionError: No Error Found, but still failed
	at prerate.prerateTestNGSlow.doPrerate(prerateTestNGSlow.java:793)
	at prerate.prerateTestNGSlow.testMethod2(prerateTestNGSlow.java:353)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testMethod2 -->
</testsuite> <!-- Prerate Test -->
